# Most version numbers are provided by build_conda.py by extraction from katana_requirements.yaml

# TODO(amp): Build variants could be generated in build_conda.py by looking for available packages which match the
#  allowed version range.

numpy:
  - 1.21

python:
  - 3.8.* *_cpython

arrow_cpp:
  - 6

pin_run_as_build:
  arrow-cpp:
    max_pin: x
  backward-cpp:
    max_pin: x
  boost-cpp:
    max_pin: x.x
  elfutils:
    min_pin: x # This means that we accept OLDER versions of elfutils at runtime. This may not be correct.
    max_pin: x
  fmt:
    max_pin: x
  libcurl:
    max_pin: x
  libxml2:
    max_pin: x
  nlohmann_json:
    max_pin: x
  numba:
    max_pin: x
  numpy:
    max_pin: x
  pyarrow:
    max_pin: x
  bliss:
    max_pin: x.x.x
