# This file may be used to create an environment using:
# $ conda env create --name <env> --file conda_recipe/environment.yml
# (This file must be named <something>.yml)
channels:
 - conda-forge
 - metagraph
dependencies:
 - arrow-cpp>=4.0,<5.0.0a0
 - backward-cpp=1.4
 - benchmark
 - black=19.10
 - breathe>=4.30
 - boost-cpp>=1.74
 - cmake>=3.17
 - conan
 - conda-build
 - conda-verify
 - cxx-compiler>=1.1.3
 - cython>=0.29.12
 - doxygen
 - eigen
 - elfutils
 - fmt>=6.2.1
 - isort
 - jemalloc
 - jinja2
 - jupyter
 - libcurl>=7.66
 - libxml2>=2.9.10
 - llvmdev>=8
 - make
 - ninja
 - ncurses>=6.1
 - nlohmann_json>=3.7.3
 - numba=0.53.1
 - numpy
 - openblas>=0.3.12
 - packaging
 - parquet-cpp
 - pyarrow
 - pydata-sphinx-theme>=0.6.3
 - pygithub
 - pytest
 - pylint=2.8.3
 - coverage
 - pandas
# CUDA-enabled build in conda fails without these, not finding /lib64/libpthread.so.0
 - gxx_linux-64
 - gcc_linux-64
 - cudatoolkit
 - cudatoolkit-dev
 - clangxx

# The dependencies for pytest-notebook are incomplete, add them manually
 - pytest-notebook
 - jupyter_client<7
 - attrs<21,>=19
 - nbconvert<6
 - nbsphinx
 - pandoc
 - pexpect
 - python=3.8.* *_cpython
 - setuptools
 - shellcheck
 - sphinx>=3.5.1,<4
 - sphinx-copybutton
 - sphinx-tabs>=2.1.0
 - zlib>=1.2.11
 - metagraph=0.2.6
